"""baseline: schema before the asme package

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-08 12:14:49.176201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('show_on_public', sa.Boolean(), nullable=False),
    sa.Column('show_on_member', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('item_condition', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('is_consumable', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('min_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('available_qty', sa.Integer(), nullable=False),
    sa.Column('nfc_tag', sa.String(length=120), nullable=True),
    sa.Column('item_code', sa.String(length=40), nullable=True),
    sa.Column('treasury_tracker_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfc_tag')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_item_code'), ['item_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_treasury_tracker_id'), ['treasury_tracker_id'], unique=True)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=160), nullable=False),
    sa.Column('requester_email', sa.String(length=160), nullable=True),
    sa.Column('room', sa.String(length=80), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('google_event_id', sa.String(length=180), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=240), nullable=True),
    sa.Column('outlook_event_id', sa.String(length=180), nullable=True),
    sa.Column('outlook_calendar_id', sa.String(length=240), nullable=True),
    sa.Column('cancel_request_token', sa.String(length=120), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cancel_request_token')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('member_class', sa.String(length=80), nullable=False),
    sa.Column('nfc_tag', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nfc_tag')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('project_type', sa.String(length=80), nullable=True),
    sa.Column('summary', sa.String(length=320), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('gallery_json', sa.Text(), nullable=True),
    sa.Column('lead_name', sa.String(length=160), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('external_link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('attendance_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('scanned_uid', sa.String(length=120), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag_value', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_tags_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_tags_tag_value'), ['tag_value'], unique=True)

    op.create_table('print_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('printer_type', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=260), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=260), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('nfc_uid', sa.String(length=160), nullable=True),
    sa.Column('major', sa.String(length=120), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('exec_title', sa.String(length=160), nullable=True),
    sa.Column('exec_message', sa.String(length=500), nullable=True),
    sa.Column('headshot_url', sa.String(length=500), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_nfc_uid'), ['nfc_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=160), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target', sa.String(length=80), nullable=True),
    sa.Column('subject', sa.String(length=220), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=220), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('calendar_event_link', sa.String(length=500), nullable=True),
    sa.Column('google_event_id', sa.String(length=220), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=260), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nfc_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_uid', sa.String(length=160), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=260), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('nfc_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nfc_tags_tag_uid'), ['tag_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_nfc_tags_user_id'), ['user_id'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('print_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('printer_type', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_link', sa.String(length=500), nullable=True),
    sa.Column('filament', sa.String(length=160), nullable=True),
    sa.Column('material', sa.String(length=120), nullable=True),
    sa.Column('color', sa.String(length=120), nullable=True),
    sa.Column('infill_percent', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=40), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('admin_notes', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_requests_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_requests_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('checkout_time', sa.DateTime(), nullable=True),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=300), nullable=True),
    sa.Column('checkout_notes', sa.String(length=300), nullable=True),
    sa.Column('return_condition', sa.String(length=120), nullable=True),
    sa.Column('return_notes', sa.String(length=300), nullable=True),
    sa.Column('return_photo_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('tag_uid', sa.String(length=160), nullable=True),
    sa.Column('checkin_method', sa.String(length=40), nullable=False),
    sa.Column('checkin_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_records_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_member_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_records_event_id'))

    op.drop_table('attendance_records')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('print_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_print_requests_member_id'))

    op.drop_table('print_requests')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('nfc_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nfc_tags_user_id'))
        batch_op.drop_index(batch_op.f('ix_nfc_tags_tag_uid'))

    op.drop_table('nfc_tags')
    op.drop_table('events')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_user_id'))

    op.drop_table('contact_messages')
    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_nfc_uid'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('print_jobs')
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_tags_tag_value'))
        batch_op.drop_index(batch_op.f('ix_item_tags_item_id'))

    op.drop_table('item_tags')
    op.drop_table('attendance_scans')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    op.drop_table('members')
    op.drop_table('meetings')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_treasury_tracker_id'))
        batch_op.drop_index(batch_op.f('ix_items_item_code'))

    op.drop_table('items')
    op.drop_table('announcements')
    # ### end Alembic commands ###
