"""launchpad, stock ledger, outbox, calendar sync, print runs

Revision ID: 0002_launchpad
Revises: 0001_baseline
Create Date: 2026-09-08 12:14:49.873910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_launchpad'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('calendar_id', sa.String(length=260), nullable=True),
    sa.Column('external_id', sa.String(length=260), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_syncs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_syncs_subject_id'), ['subject_id'], unique=False)

    op.create_table('onboarding_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onboarding_tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_tracks_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_tracks_key'), ['key'], unique=True)

    op.create_table('outbox_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_jobs_run_at'), ['run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_jobs_status'), ['status'], unique=False)

    op.create_table('training_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_modules_key'), ['key'], unique=True)

    op.create_table('onboarding_phases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('grants_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['onboarding_tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'key', name='uq_phase_track_key')
    )
    with op.batch_alter_table('onboarding_phases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_phases_track_id'), ['track_id'], unique=False)

    op.create_table('entitlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('granted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.create_index('ix_entitlement_user_key', ['user_id', 'key'], unique=False)
        batch_op.create_index(batch_op.f('ix_entitlements_user_id'), ['user_id'], unique=False)

    op.create_table('onboarding_phase_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['onboarding_phases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'subject_type', 'subject_id', name='uq_phase_state_subject')
    )
    with op.batch_alter_table('onboarding_phase_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_phase_states_phase_id'), ['phase_id'], unique=False)
        batch_op.create_index('ix_phase_state_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('onboarding_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=True),
    sa.Column('rule_type', sa.String(length=40), nullable=False),
    sa.Column('rule_config_json', sa.Text(), nullable=False),
    sa.Column('cta_route', sa.String(length=200), nullable=True),
    sa.Column('cta_label', sa.String(length=80), nullable=True),
    sa.Column('help_url', sa.String(length=500), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['onboarding_phases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phase_id', 'key', name='uq_task_phase_key')
    )
    with op.batch_alter_table('onboarding_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_tasks_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_onboarding_tasks_phase_id'), ['phase_id'], unique=False)

    op.create_table('project_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_membership')
    )
    with op.batch_alter_table('project_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_memberships_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('stock_discrepancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('counter_available', sa.Integer(), nullable=False),
    sa.Column('derived_available', sa.Integer(), nullable=False),
    sa.Column('open_loan_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_discrepancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_discrepancies_item_id'), ['item_id'], unique=False)

    op.create_table('training_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_completions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_completions_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_completions_user_id'), ['user_id'], unique=False)

    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('hours', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('logged_for', sa.Date(), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_logs_user_id'), ['user_id'], unique=False)

    op.create_table('onboarding_task_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('subject_type', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['onboarding_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'subject_type', 'subject_id', name='uq_task_state_subject')
    )
    with op.batch_alter_table('onboarding_task_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_onboarding_task_states_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_task_state_subject', ['subject_type', 'subject_id'], unique=False)

    op.create_table('print_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('printer_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_by_user_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['print_requests.id'], ),
    sa.ForeignKeyConstraint(['started_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_runs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_print_runs_status'), ['status'], unique=False)

    op.create_table('stock_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('delta_available', sa.Integer(), nullable=False),
    sa.Column('delta_total', sa.Integer(), nullable=False),
    sa.Column('available_after', sa.Integer(), nullable=True),
    sa.Column('total_after', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_ledger_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_transaction_id'), ['transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_ledger_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_records_checkin_time'), ['checkin_time'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=40), nullable=False, server_default='meeting'))
        batch_op.create_index(batch_op.f('ix_events_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    with op.batch_alter_table('print_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_print_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_joinable', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('signed_off_by_user_id', sa.Integer(), nullable=True))
        batch_op.alter_column('member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_transactions_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_unique_constraint('uq_transactions_idempotency_key', ['idempotency_key'])
        batch_op.create_foreign_key('fk_transactions_signed_off_by_user_id_users', 'users', ['signed_off_by_user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###

    _backfill_data()


def _backfill_data():
    """Data migration for databases that predate the asme package.

    * ``transactions.user_id`` from the legacy member's email (Stage 4 of the
      blueprint: ``User`` becomes the canonical borrower).
    * inventory tracking ids that the old app generated lazily at runtime.
    * one ``item_tags`` row per legacy ``items.nfc_tag`` so multi-tag lookups work.
    """
    import re

    bind = op.get_bind()

    bind.execute(sa.text(
        "UPDATE transactions SET user_id = ("
        "  SELECT u.id FROM users u JOIN members m ON lower(u.email) = lower(m.email)"
        "  WHERE m.id = transactions.member_id LIMIT 1"
        ") WHERE user_id IS NULL AND member_id IS NOT NULL"
    ))
    bind.execute(sa.text("UPDATE events SET kind = 'meeting' WHERE kind IS NULL OR kind = ''"))
    bind.execute(sa.text("UPDATE projects SET is_joinable = 1 WHERE is_joinable IS NULL"))
    bind.execute(sa.text(
        "UPDATE items SET item_type = COALESCE(NULLIF(item_type, ''), 'tool'), "
        "is_consumable = COALESCE(is_consumable, 0), active = COALESCE(active, 1), "
        "min_stock_threshold = COALESCE(min_stock_threshold, 0)"
    ))

    def _norm(value, limit):
        cleaned = re.sub(r"[^A-Z0-9\-]+", "-", (value or "").strip().upper())
        return re.sub(r"-{2,}", "-", cleaned).strip("-")[:limit]

    rows = bind.execute(sa.text("SELECT id, item_code, treasury_tracker_id, nfc_tag FROM items ORDER BY id")).fetchall()
    used_codes = {_norm(r[1], 40).lower() for r in rows if r[1]}
    used_trackers = {_norm(r[2], 80).lower() for r in rows if r[2]}
    for item_id, item_code, tracker_id, nfc_tag in rows:
        code = _norm(item_code, 40)
        if not code:
            code = f"ASME-INV-{int(item_id):05d}"
            base, n = code, 2
            while code.lower() in used_codes:
                code = _norm(f"{base}-{n}", 40)
                n += 1
            used_codes.add(code.lower())
            bind.execute(sa.text("UPDATE items SET item_code = :code WHERE id = :id"), {"code": code, "id": item_id})
        tracker = _norm(tracker_id, 80)
        if not tracker:
            suffix = code[len("ASME-INV-"):] if code.startswith("ASME-INV-") else code
            tracker = _norm(f"ASME-TRK-{suffix}", 80)
            base, n = tracker, 2
            while tracker.lower() in used_trackers:
                tracker = _norm(f"{base}-{n}", 80)
                n += 1
            used_trackers.add(tracker.lower())
            bind.execute(sa.text("UPDATE items SET treasury_tracker_id = :tracker WHERE id = :id"), {"tracker": tracker, "id": item_id})
        tag = " ".join((nfc_tag or "").split())
        if tag:
            exists = bind.execute(sa.text("SELECT 1 FROM item_tags WHERE lower(tag_value) = lower(:tag)"), {"tag": tag}).first()
            if not exists:
                bind.execute(
                    sa.text(
                        "INSERT INTO item_tags (item_id, tag_value, source, created_at) "
                        "VALUES (:item_id, :tag, 'legacy_item_tag', CURRENT_TIMESTAMP)"
                    ),
                    {"item_id": item_id, "tag": tag},
                )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_signed_off_by_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('uq_transactions_idempotency_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_member_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_item_id'))
        batch_op.alter_column('member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('signed_off_by_user_id')
        batch_op.drop_column('idempotency_key')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('is_joinable')

    with op.batch_alter_table('print_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_requests_status'))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_start_time'))
        batch_op.drop_column('kind')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_records_checkin_time'))

    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_ledger_created_at'))

    op.drop_table('stock_ledger')
    with op.batch_alter_table('print_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_print_runs_status'))
        batch_op.drop_index(batch_op.f('ix_print_runs_request_id'))

    op.drop_table('print_runs')
    with op.batch_alter_table('onboarding_task_states', schema=None) as batch_op:
        batch_op.drop_index('ix_task_state_subject')
        batch_op.drop_index(batch_op.f('ix_onboarding_task_states_task_id'))

    op.drop_table('onboarding_task_states')
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_logs_project_id'))

    op.drop_table('work_logs')
    with op.batch_alter_table('training_completions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_completions_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_completions_module_id'))

    op.drop_table('training_completions')
    with op.batch_alter_table('stock_discrepancies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_discrepancies_item_id'))

    op.drop_table('stock_discrepancies')
    with op.batch_alter_table('project_memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_memberships_project_id'))

    op.drop_table('project_memberships')
    with op.batch_alter_table('onboarding_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_tasks_phase_id'))
        batch_op.drop_index(batch_op.f('ix_onboarding_tasks_key'))

    op.drop_table('onboarding_tasks')
    with op.batch_alter_table('onboarding_phase_states', schema=None) as batch_op:
        batch_op.drop_index('ix_phase_state_subject')
        batch_op.drop_index(batch_op.f('ix_onboarding_phase_states_phase_id'))

    op.drop_table('onboarding_phase_states')
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entitlements_user_id'))
        batch_op.drop_index('ix_entitlement_user_key')

    op.drop_table('entitlements')
    with op.batch_alter_table('onboarding_phases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_phases_track_id'))

    op.drop_table('onboarding_phases')
    with op.batch_alter_table('training_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_modules_key'))

    op.drop_table('training_modules')
    with op.batch_alter_table('outbox_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_outbox_jobs_run_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_jobs_kind'))

    op.drop_table('outbox_jobs')
    with op.batch_alter_table('onboarding_tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_onboarding_tracks_key'))
        batch_op.drop_index(batch_op.f('ix_onboarding_tracks_audience'))

    op.drop_table('onboarding_tracks')
    with op.batch_alter_table('calendar_syncs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_syncs_subject_id'))

    op.drop_table('calendar_syncs')
    # ### end Alembic commands ###
