"""ops foundation: organisations, roles, teams, locations, categories, assets, projects, work orders, files, audit

Revision ID: 0003_ops_foundation
Revises: 0002_launchpad
Create Date: 2026-09-08 20:07:19.999090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_ops_foundation'
down_revision = '0002_launchpad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('academic_year_start_month', sa.Integer(), nullable=False),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_key'), ['key'], unique=True)

    op.create_table('work_order_counters',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_work_order_counters_organization_id_organizations')),
    sa.PrimaryKeyConstraint('organization_id', name=op.f('pk_work_order_counters'))
    )
    op.create_table('asset_types',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_asset_types_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_asset_types_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_asset_types_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_types')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_asset_types_org_name')
    )
    with op.batch_alter_table('asset_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_types_organization_id'), ['organization_id'], unique=False)

    op.create_table('attachments',
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=260), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_attachments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attachments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_attachments_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_attachments_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_attachments_storage_key'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('before_json', sa.Text(), nullable=True),
    sa.Column('after_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=120), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index('ix_audit_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('categories',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_categories_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_categories_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_categories_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_categories_org_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_organization_id'), ['organization_id'], unique=False)

    op.create_table('comments',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_comments_author_user_id_users')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_comments_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_comments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name=op.f('fk_comments_parent_comment_id_comments')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_comments_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_user_id'), ['author_user_id'], unique=False)
        batch_op.create_index('ix_comments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_organization_id'), ['organization_id'], unique=False)

    op.create_table('locations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_location_id', sa.String(length=36), nullable=True),
    sa.Column('building', sa.String(length=160), nullable=True),
    sa.Column('room', sa.String(length=80), nullable=True),
    sa.Column('address_json', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('qr_code', sa.String(length=120), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_locations_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_locations_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_location_id'], ['locations.id'], name=op.f('fk_locations_parent_location_id_locations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_locations_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_locations_parent_location_id'), ['parent_location_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_notifications_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_notifications_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('ops_projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('lead_user_id', sa.Integer(), nullable=True),
    sa.Column('faculty_advisor_user_id', sa.Integer(), nullable=True),
    sa.Column('competition', sa.String(length=200), nullable=True),
    sa.Column('academic_year', sa.String(length=9), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_code', sa.String(length=60), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('cad_url', sa.String(length=500), nullable=True),
    sa.Column('requirements_url', sa.String(length=500), nullable=True),
    sa.Column('public_project_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_ops_projects_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['faculty_advisor_user_id'], ['users.id'], name=op.f('fk_ops_projects_faculty_advisor_user_id_users')),
    sa.ForeignKeyConstraint(['lead_user_id'], ['users.id'], name=op.f('fk_ops_projects_lead_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ops_projects_organization_id_organizations')),
    sa.ForeignKeyConstraint(['public_project_id'], ['projects.id'], name=op.f('fk_ops_projects_public_project_id_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_ops_projects_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ops_projects')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_ops_projects_org_code'),
    sa.UniqueConstraint('public_project_id', name=op.f('uq_ops_projects_public_project_id'))
    )
    with op.batch_alter_table('ops_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ops_projects_lead_user_id'), ['lead_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ops_projects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ops_projects_status'), ['status'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('system_key', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_roles_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_roles_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_roles_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_roles_org_name')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_system_key'), ['system_key'], unique=False)

    op.create_table('memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('member_status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('settings_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_memberships_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_memberships_role_id_roles')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_memberships_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership_org_user')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('milestones',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_milestones_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_milestones_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_milestones_owner_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['ops_projects.id'], name=op.f('fk_milestones_project_id_ops_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_milestones_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_milestones'))
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestones_project_id'), ['project_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('permission_id', sa.String(length=36), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_permissions_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_role_permissions_role_id'), ['role_id'], unique=False)

    op.create_table('teams',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_team_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('escalation_note', sa.String(length=500), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_teams_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_teams_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_team_id'], ['teams.id'], name=op.f('fk_teams_parent_team_id_teams')),
    sa.ForeignKeyConstraint(['project_id'], ['ops_projects.id'], name=op.f('fk_teams_project_id_ops_projects')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_teams_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_teams_org_name')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_parent_team_id'), ['parent_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_project_id'), ['project_id'], unique=False)

    op.create_table('assets',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parent_asset_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('responsible_team_id', sa.String(length=36), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=160), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('serial_number', sa.String(length=160), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('warranty_end', sa.Date(), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('qr_code', sa.String(length=120), nullable=True),
    sa.Column('photo_attachment_id', sa.String(length=36), nullable=True),
    sa.Column('custom_fields_json', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_assets_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_assets_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_assets_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_assets_owner_user_id_users')),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.id'], name=op.f('fk_assets_parent_asset_id_assets')),
    sa.ForeignKeyConstraint(['project_id'], ['ops_projects.id'], name=op.f('fk_assets_project_id_ops_projects')),
    sa.ForeignKeyConstraint(['responsible_team_id'], ['teams.id'], name=op.f('fk_assets_responsible_team_id_teams')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_assets_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_assets_org_code')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_parent_asset_id'), ['parent_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_responsible_team_id'), ['responsible_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_status'), ['status'], unique=False)

    op.create_table('ops_project_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('project_role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['ops_projects.id'], name=op.f('fk_ops_project_members_project_id_ops_projects')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_ops_project_members_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ops_project_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ops_project_members')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_ops_project_member')
    )
    with op.batch_alter_table('ops_project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ops_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ops_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('saved_filters',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('filter_json', sa.Text(), nullable=False),
    sa.Column('sort_json', sa.Text(), nullable=False),
    sa.Column('view_type', sa.String(length=30), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_saved_filters_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_saved_filters_organization_id_organizations')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_saved_filters_owner_user_id_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_saved_filters_team_id_teams')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_saved_filters_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_filters'))
    )
    with op.batch_alter_table('saved_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_filters_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_filters_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_filters_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('team_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members')),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('asset_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('downtime_type', sa.String(length=30), nullable=True),
    sa.Column('downtime_reason', sa.String(length=160), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_status_history_asset_id_assets')),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_asset_status_history_changed_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_status_history'))
    )
    with op.batch_alter_table('asset_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_status_history_asset_id'), ['asset_id'], unique=False)

    op.create_table('asset_type_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('asset_type_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_asset_type_links_asset_id_assets')),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], name=op.f('fk_asset_type_links_asset_type_id_asset_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_type_links')),
    sa.UniqueConstraint('asset_id', 'asset_type_id', name='uq_asset_type_link')
    )
    with op.batch_alter_table('asset_type_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_type_links_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_type_links_asset_type_id'), ['asset_type_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=30), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('primary_asset_id', sa.String(length=36), nullable=True),
    sa.Column('parent_work_order_id', sa.String(length=36), nullable=True),
    sa.Column('source_request_id', sa.String(length=36), nullable=True),
    sa.Column('maintenance_plan_id', sa.String(length=36), nullable=True),
    sa.Column('generation_key', sa.String(length=120), nullable=True),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('budget_code', sa.String(length=60), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('recurring_rule_json', sa.Text(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=500), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('parent_completion_policy', sa.String(length=20), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_work_orders_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_work_orders_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_work_orders_organization_id_organizations')),
    sa.ForeignKeyConstraint(['parent_work_order_id'], ['work_orders.id'], name=op.f('fk_work_orders_parent_work_order_id_work_orders')),
    sa.ForeignKeyConstraint(['primary_asset_id'], ['assets.id'], name=op.f('fk_work_orders_primary_asset_id_assets')),
    sa.ForeignKeyConstraint(['project_id'], ['ops_projects.id'], name=op.f('fk_work_orders_project_id_ops_projects')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_work_orders_team_id_teams')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_work_orders_updated_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_orders')),
    sa.UniqueConstraint('generation_key', name=op.f('uq_work_orders_generation_key')),
    sa.UniqueConstraint('organization_id', 'number', name='uq_work_orders_org_number')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index('ix_work_orders_due', ['organization_id', 'due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_location_id'), ['location_id'], unique=False)
        batch_op.create_index('ix_work_orders_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_parent_work_order_id'), ['parent_work_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_primary_asset_id'), ['primary_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_team_id'), ['team_id'], unique=False)

    op.create_table('cost_entries',
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vendor_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_cost_entries_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_cost_entries_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_cost_entries_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_cost_entries_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_entries'))
    )
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cost_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_entries_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('time_entries',
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_time_entries_created_by_user_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_time_entries_organization_id_organizations')),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_time_entries_updated_by_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_time_entries_user_id_users')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_time_entries_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_time_entries'))
    )
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entries_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entries_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], name=op.f('fk_work_order_assets_asset_id_assets')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_assets_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_assets')),
    sa.UniqueConstraint('work_order_id', 'asset_id', name='uq_wo_asset')
    )
    with op.batch_alter_table('work_order_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_assets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_assets_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_assignees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], name=op.f('fk_work_order_assignees_assigned_by_user_id_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_work_order_assignees_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_work_order_assignees_user_id_users')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_assignees_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_assignees')),
    sa.UniqueConstraint('work_order_id', 'team_id', name='uq_wo_assignee_team'),
    sa.UniqueConstraint('work_order_id', 'user_id', name='uq_wo_assignee_user')
    )
    with op.batch_alter_table('work_order_assignees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_assignees_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_assignees_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_assignees_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_work_order_categories_category_id_categories')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_categories_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_categories')),
    sa.UniqueConstraint('work_order_id', 'category_id', name='uq_wo_category')
    )
    with op.batch_alter_table('work_order_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_categories_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_categories_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_dependencies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('blocking_work_order_id', sa.String(length=36), nullable=False),
    sa.Column('blocked_work_order_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['blocked_work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_dependencies_blocked_work_order_id_work_orders')),
    sa.ForeignKeyConstraint(['blocking_work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_dependencies_blocking_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_dependencies')),
    sa.UniqueConstraint('blocking_work_order_id', 'blocked_work_order_id', name='uq_wo_dependency')
    )
    with op.batch_alter_table('work_order_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_dependencies_blocked_work_order_id'), ['blocked_work_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_dependencies_blocking_work_order_id'), ['blocking_work_order_id'], unique=False)

    op.create_table('work_order_status_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_work_order_status_history_changed_by_user_id_users')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_status_history_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_status_history'))
    )
    with op.batch_alter_table('work_order_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_status_history_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_watchers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_work_order_watchers_user_id_users')),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name=op.f('fk_work_order_watchers_work_order_id_work_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_order_watchers')),
    sa.UniqueConstraint('work_order_id', 'user_id', name='uq_wo_watcher')
    )
    with op.batch_alter_table('work_order_watchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_watchers_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_order_watchers_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_watchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_watchers_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_watchers_user_id'))

    op.drop_table('work_order_watchers')
    with op.batch_alter_table('work_order_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_status_history_work_order_id'))

    op.drop_table('work_order_status_history')
    with op.batch_alter_table('work_order_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_dependencies_blocking_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_dependencies_blocked_work_order_id'))

    op.drop_table('work_order_dependencies')
    with op.batch_alter_table('work_order_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_categories_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_categories_category_id'))

    op.drop_table('work_order_categories')
    with op.batch_alter_table('work_order_assignees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_assignees_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_assignees_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_assignees_team_id'))

    op.drop_table('work_order_assignees')
    with op.batch_alter_table('work_order_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_assets_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_order_assets_asset_id'))

    op.drop_table('work_order_assets')
    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entries_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_time_entries_organization_id'))

    op.drop_table('time_entries')
    with op.batch_alter_table('cost_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cost_entries_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_cost_entries_organization_id'))

    op.drop_table('cost_entries')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_team_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_project_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_primary_asset_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_parent_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_organization_id'))
        batch_op.drop_index('ix_work_orders_org_status')
        batch_op.drop_index(batch_op.f('ix_work_orders_location_id'))
        batch_op.drop_index('ix_work_orders_due')

    op.drop_table('work_orders')
    with op.batch_alter_table('asset_type_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_type_links_asset_type_id'))
        batch_op.drop_index(batch_op.f('ix_asset_type_links_asset_id'))

    op.drop_table('asset_type_links')
    with op.batch_alter_table('asset_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_status_history_asset_id'))

    op.drop_table('asset_status_history')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))

    op.drop_table('team_members')
    with op.batch_alter_table('saved_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_filters_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_filters_organization_id'))
        batch_op.drop_index(batch_op.f('ix_saved_filters_entity_type'))

    op.drop_table('saved_filters')
    with op.batch_alter_table('ops_project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ops_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_ops_project_members_project_id'))

    op.drop_table('ops_project_members')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_status'))
        batch_op.drop_index(batch_op.f('ix_assets_responsible_team_id'))
        batch_op.drop_index(batch_op.f('ix_assets_project_id'))
        batch_op.drop_index(batch_op.f('ix_assets_parent_asset_id'))
        batch_op.drop_index(batch_op.f('ix_assets_organization_id'))
        batch_op.drop_index(batch_op.f('ix_assets_location_id'))

    op.drop_table('assets')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_project_id'))
        batch_op.drop_index(batch_op.f('ix_teams_parent_team_id'))
        batch_op.drop_index(batch_op.f('ix_teams_organization_id'))

    op.drop_table('teams')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_permissions_role_id'))
        batch_op.drop_index(batch_op.f('ix_role_permissions_permission_id'))

    op.drop_table('role_permissions')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_project_id'))
        batch_op.drop_index(batch_op.f('ix_milestones_organization_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_role_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_system_key'))
        batch_op.drop_index(batch_op.f('ix_roles_organization_id'))

    op.drop_table('roles')
    with op.batch_alter_table('ops_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ops_projects_status'))
        batch_op.drop_index(batch_op.f('ix_ops_projects_organization_id'))
        batch_op.drop_index(batch_op.f('ix_ops_projects_lead_user_id'))

    op.drop_table('ops_projects')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_parent_location_id'))
        batch_op.drop_index(batch_op.f('ix_locations_organization_id'))

    op.drop_table('locations')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_organization_id'))
        batch_op.drop_index('ix_comments_entity')
        batch_op.drop_index(batch_op.f('ix_comments_author_user_id'))

    op.drop_table('comments')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_organization_id'))

    op.drop_table('categories')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_type'))
        batch_op.drop_index('ix_audit_events_entity')
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))

    op.drop_table('audit_events')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_uploaded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_organization_id'))
        batch_op.drop_index('ix_attachments_entity')

    op.drop_table('attachments')
    with op.batch_alter_table('asset_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_types_organization_id'))

    op.drop_table('asset_types')
    op.drop_table('work_order_counters')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_key'))

    op.drop_table('permissions')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
