param(
  [string]$RepoRoot = (Resolve-Path "$PSScriptRoot\..").Path
)

$ErrorActionPreference = "Stop"

function Write-Step($text) {
  Write-Host ""
  Write-Host "==> $text"
}

Set-Location $RepoRoot

Write-Step "Installing/Updating bambu-cli for this Python user"
python -m pip install bambu-cli

Write-Step "Adding local printers (run this once per printer you want to use)"
Write-Host "When prompted, select printer and enter LAN access code from printer settings."
python -m bambucli.cli add-local

$addSecond = Read-Host "Add another printer now? (y/N)"
if ($addSecond -match '^(y|Y)$') {
  python -m bambucli.cli add-local
}

$printersPath = Join-Path $HOME ".bambu-cli\printers.json"
if (!(Test-Path $printersPath)) {
  throw "No printer config found at $printersPath. Could not continue."
}

$printersJson = Get-Content $printersPath -Raw | ConvertFrom-Json
$printerNames = @($printersJson.PSObject.Properties.Name)
if ($printerNames.Count -eq 0) {
  throw "No printers were saved in $printersPath."
}

Write-Step "Detected printers"
for ($i = 0; $i -lt $printerNames.Count; $i++) {
  Write-Host "$($i + 1)) $($printerNames[$i])"
}

$h2sName = Read-Host "Enter printer name to use for H2S queue"
$p1sName = Read-Host "Enter printer name to use for P1S queue"

if ([string]::IsNullOrWhiteSpace($h2sName) -or [string]::IsNullOrWhiteSpace($p1sName)) {
  throw "Both H2S and P1S printer names are required."
}

$envPath = Join-Path $RepoRoot "instance\print_commands.env"
if (!(Test-Path (Split-Path $envPath -Parent))) {
  New-Item -ItemType Directory -Path (Split-Path $envPath -Parent) | Out-Null
}

$content = @(
  "# Auto-generated by scripts/setup_bambu_print.ps1",
  "ASME_H2S_PRINT_CMD=python -m bambucli.cli print `"$h2sName`" `"{file}`"",
  "ASME_P1S_PRINT_CMD=python -m bambucli.cli print `"$p1sName`" `"{file}`""
)
Set-Content -Path $envPath -Value $content -Encoding UTF8

Write-Step "Saved printer commands"
Write-Host $envPath
Write-Host ""
Write-Host "Next: restart app.py, then submit a print job."
